version: '3.9'

services:
  products:
    build: ./products_service
    ports:
      - 8000:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/__health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    depends_on:
      - db

  db:
    image: postgres:14.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: diana
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microdb
    ports: 
      - 5432:5432

volumes:
  postgres_data:
