name: Docker Image CI

on:
  push:
    branches: ["master"]

jobs:
  test-push: 
    runs-on: ubuntu-latest

  services:
    postgres:
      image: postgres
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: microdb
      ports:
        - 5432:5432
      options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Build the test Docker image
      run: docker build . --file Dockerfile -t bluero/products-service:latest
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      
    - name: Install packages
      run: pip install pytest requests
    
    - name: Run tests
      run: pytest
        


    - name: Login into Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push tag to Docker Hub
      run: docker push bluero/products-service:latest
